---
name: edwisely
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_bloc: ^6.0.5
  dio: ^3.0.10
  intl: ^0.16.1
  file_picker_cross: ^4.2.1
  flutter_duration_picker: ^1.0.4
  dropdown_search: ^0.4.4
  chips_choice: ^1.2.0
  toast: ^0.1.5
  provider: ^4.3.2+2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Regular.ttf
        - asset: fonts/Poppins/Poppins-Italic.ttf
          style: italic

