---
name: edwisely
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_bloc: ^6.0.5
  dio: ^3.0.10
  intl: ^0.16.1
  file_picker_cross: ^4.2.2
  flutter_duration_picker: ^1.0.4
  chips_choice: ^1.2.0
  toast: ^0.1.5
  image_picker: ^0.6.7+11
  image_picker_for_web: ^0.1.0+2
  shared_preferences_web: ^0.1.2+7
  shared_preferences: ^0.5.12
  flutter_svg: ^0.19.0
  auto_size_text: ^2.1.0
  flutter_datetime_picker: ^1.4.0
  provider: ^4.3.2+2
  flutter_typeahead: ^1.8.8

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - assets/icons/add_course_material.svg
  - assets/icons/conduct_live_assesment.svg
  - assets/icons/conduct_live_class.svg
  - assets/icons/get_feedback.svg
  - assets/icons/my_assesment.svg
  - assets/icons/recently_viewed.svg
  - assets/icons/schedule_event.svg
  - assets/icons/send_assignment.svg
  - assets/icons/send_notification.svg
  - assets/images/login_screen.png
  - assets/placeholder_image.jpg
  - assets/logo/
  fonts:
  - family: Poppins
    fonts:
    - asset: fonts/Poppins/Poppins-Regular.ttf
    - asset: fonts/Poppins/Poppins-Italic.ttf
      style: italic
