/// Generated by AssetsRefGenerator on 2020/09/22
class Res {
  static const String add_course_material =
      "assets/icons/add_course_material.svg";
  static const String conduct_live_assesment =
      "assets/icons/conduct_live_assesment.svg";
  static const String conduct_live_class =
      "assets/icons/conduct_live_class.svg";
  static const String get_feedback = "assets/icons/get_feedback.svg";
  static const String my_assesment = "assets/icons/my_assesment.svg";
  static const String recently_viewed = "assets/icons/recently_viewed.svg";
  static const String schedule_event = "assets/icons/schedule_event.svg";
  static const String send_assignment = "assets/icons/send_assignment.svg";
  static const String send_notification = "assets/icons/send_notification.svg";
  static const String login_screen = "assets/images/login_screen.png";
  static const String placeholder_image = "assets/placeholder_image.jpg";
}
